name = "Bloatprint"
author = "Charliemineboy & ItsPercent"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a855c1be6ad700cb6d5b165b2dd5ece1bb90134b5ec089068eecabfaa6bbc3b9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.226"
