name = "Bloatprint"
author = "Charliemineboy & ItsPercent"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c90a561f1e797420dda4eff781c05a33a589f8ab874df11cc44599fff893088"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.226"

[options]
datapack-folder = "datapacks"
